steps:
  - label: "Checkout code"
    command: "echo 'Code checkout done'"
    agents:
      queue: "amd-buildkite"

  - label: "Build & push multi-arch Docker image"
    commands:
      - echo "DOCKER_USERNAME is: $DOCKER_USERNAME"
      - docker buildx create --use
      - docker login
      - docker buildx build --platform linux/amd64,linux/arm64 -t "$DOCKER_USERNAME/test-x86:latest" --push .
    agents:
      queue: "amd-buildkite"
